//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.02 at 08:59:16 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.niren.com/base/bo/Status")
package com.niren.base.bo.status;
